# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SITECORE_SITE_NAME: ${{ secrets.SITECORE_SITE_NAME }}
  JSS_EDITING_SECRET: ${{ secrets.JSS_EDITING_SECRET }}
  SITECORE_EDGE_CONTEXT_ID: ${{ secrets.SITECORE_EDGE_CONTEXT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      
      - name: Create .env.production file
        run: |
          echo "SITECORE_SITE_NAME=${{ secrets.SITECORE_SITE_NAME }}" >> .env.production
          echo "JSS_EDITING_SECRET=${{ secrets.JSS_EDITING_SECRET }}" >> .env.production
          echo "FETCH_WITH=GraphQL" >> .env.production
          echo "GRAPH_QL_SERVICE_RETRIES=3" >> .env.production
          echo "SITECORE_EDGE_CONTEXT_ID=${{ secrets.SITECORE_EDGE_CONTEXT_ID }}" >> .env.production
          echo "PUBLIC_URL=${{ secrets.PUBLIC_URL }}" >> .env.production
        shell: bash
        working-directory: ./headapps/nextjs-starter

      - name: npm install, build, and test
        shell: bash
        working-directory: ./headapps/nextjs-starter
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: print .next after the build
        working-directory: ./headapps/nextjs-starter/.next
        run: |
          tree -a -L 4 -I node_modules

      - name: Prepare standalone deployment package
        run: |
          mkdir -p deploy/.next/static
          cp -r .next/standalone/. deploy/
          cp -r .next/static/. deploy/.next/static
          cp -r public deploy/public || true
          cp package.json deploy/
        working-directory: ./headapps/nextjs-starter

      - name: print deploy after copying build output
        working-directory: ./headapps/nextjs-starter/deploy
        run: |
          tree -a -L 4 -I node_modules

      - name: Zip deployment package
        run: |
          cd deploy
          zip -r ../deploy.zip .
        working-directory: ./headapps/nextjs-starter

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./headapps/nextjs-starter/deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_NAME }}
          slot-name: 'Production'
          package: deploy.zip